// <auto-generated />
using System;
using LTMS.Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CleanArchitectureSampleDesing.Infrastructure.Persistance.Migrations
{
    [DbContext(typeof(CleanArchitectureSampleDesingDbContext))]
    [Migration("20230310124040_addnewapp")]
    partial class addnewapp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LTMS.Domain.Model.ActivityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ActivityType");
                });

            modelBuilder.Entity("LTMS.Domain.Model.AuditType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActivityTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActivityTypeId");

                    b.ToTable("AuditTypes");
                });

            modelBuilder.Entity("CleanArchitectureSampleDesing.Domain.Model.BrandType", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BrandType", (string)null);
                });

            modelBuilder.Entity("CleanArchitectureSampleDesing.Domain.Model.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InternalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("ItemSubCatagoryId")
                        .HasColumnType("smallint");

                    b.Property<short>("ItemUnitTypeId")
                        .HasColumnType("smallint");

                    b.Property<short>("ModelTypeId")
                        .HasColumnType("smallint");

                    b.Property<string>("StandardCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ItemSubCatagoryId");

                    b.HasIndex("ItemUnitTypeId");

                    b.HasIndex("ModelTypeId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("CleanArchitectureSampleDesing.Domain.Model.ItemCatagory", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ItemCatagory", (string)null);
                });

            modelBuilder.Entity("CleanArchitectureSampleDesing.Domain.Model.ItemImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemImage", (string)null);
                });

            modelBuilder.Entity("CleanArchitectureSampleDesing.Domain.Model.ItemOption", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("OptionGroupTypeId")
                        .HasColumnType("int");

                    b.Property<int>("OptionTypeId")
                        .HasColumnType("int");

                    b.Property<string>("OptionValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("OptionGroupTypeId");

                    b.HasIndex("OptionTypeId");

                    b.ToTable("ItemOption", (string)null);
                });

            modelBuilder.Entity("CleanArchitectureSampleDesing.Domain.Model.ItemSubCatagory", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<short>("ItemCatagoryId")
                        .HasColumnType("smallint");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ItemCatagoryId");

                    b.ToTable("ItemSubCatagory", (string)null);
                });

            modelBuilder.Entity("CleanArchitectureSampleDesing.Domain.Model.ItemUnitType", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ItemUnitType", (string)null);
                });

            modelBuilder.Entity("CleanArchitectureSampleDesing.Domain.Model.ModelType", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<short>("BrandTypeId")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BrandTypeId");

                    b.ToTable("ModelType", (string)null);
                });

            modelBuilder.Entity("CleanArchitectureSampleDesing.Domain.Model.OptionGroupType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OptionGroupType", (string)null);
                });

            modelBuilder.Entity("CleanArchitectureSampleDesing.Domain.Model.OptionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OptionType", (string)null);
                });

            modelBuilder.Entity("LTMS.Domain.Model.AuditType", b =>
                {
                    b.HasOne("LTMS.Domain.Model.ActivityType", "ActivityType")
                        .WithMany()
                        .HasForeignKey("ActivityTypeId");

                    b.Navigation("ActivityType");
                });

            modelBuilder.Entity("CleanArchitectureSampleDesing.Domain.Model.Item", b =>
                {
                    b.HasOne("CleanArchitectureSampleDesing.Domain.Model.ItemSubCatagory", "ItemSubCatagory")
                        .WithMany()
                        .HasForeignKey("ItemSubCatagoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchitectureSampleDesing.Domain.Model.ItemUnitType", "ItemUnitType")
                        .WithMany()
                        .HasForeignKey("ItemUnitTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchitectureSampleDesing.Domain.Model.ModelType", "ModelType")
                        .WithMany()
                        .HasForeignKey("ModelTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemSubCatagory");

                    b.Navigation("ItemUnitType");

                    b.Navigation("ModelType");
                });

            modelBuilder.Entity("CleanArchitectureSampleDesing.Domain.Model.ItemImage", b =>
                {
                    b.HasOne("CleanArchitectureSampleDesing.Domain.Model.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("CleanArchitectureSampleDesing.Domain.Model.ItemOption", b =>
                {
                    b.HasOne("CleanArchitectureSampleDesing.Domain.Model.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchitectureSampleDesing.Domain.Model.OptionGroupType", "OptionGroupType")
                        .WithMany()
                        .HasForeignKey("OptionGroupTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchitectureSampleDesing.Domain.Model.OptionType", "OptionType")
                        .WithMany()
                        .HasForeignKey("OptionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("OptionGroupType");

                    b.Navigation("OptionType");
                });

            modelBuilder.Entity("CleanArchitectureSampleDesing.Domain.Model.ItemSubCatagory", b =>
                {
                    b.HasOne("CleanArchitectureSampleDesing.Domain.Model.ItemCatagory", "ItemCatagory")
                        .WithMany()
                        .HasForeignKey("ItemCatagoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemCatagory");
                });

            modelBuilder.Entity("CleanArchitectureSampleDesing.Domain.Model.ModelType", b =>
                {
                    b.HasOne("CleanArchitectureSampleDesing.Domain.Model.BrandType", "BrandType")
                        .WithMany()
                        .HasForeignKey("BrandTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BrandType");
                });
#pragma warning restore 612, 618
        }
    }
}
